alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: REDIS_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: default
- key: REDIS_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: my-password
- key: REDIS_HOST
  scope: RUN_AND_BUILD_TIME
  value: my-redis.db.ondigitalocean.com
- key: REDIS_PORT
  scope: RUN_AND_BUILD_TIME
  value: "25061"
- key: ALLOWED_HOSTS
  scope: RUN_AND_BUILD_TIME
  value: ${APP_DOMAIN}
- key: DEBUG_MODE
  scope: RUN_AND_BUILD_TIME
  value: "1"
ingress:
  rules:
  - component:
      name: dj-daphne
    match:
      path:
        prefix: /
name: dj-daphne-app
region: fra
services:
- environment_slug: python
  github:
    branch: main
    repo: adnankaya/dj-daphne
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  name: dj-daphne
  run_command: daphne -b 0.0.0.0 -p 8080 src.asgi:application
  source_dir: /
